### ISSUE TITLE
k8s-infra: generic installation docs based on cloud vendor

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz.io#300]
We recently had couple of users who asked for installation steps for GKE Autopilot.

It would also help to have custom resource detectors set up based on K8s cloud vendor.

**Comment by Calm-Rock** [comment]
Related issues : 
- https://github.com/SigNoz/engineering-pod/issues/1373
- https://github.com/SigNoz/engineering-pod/issues/1372
