### ISSUE TITLE
Create docs for APIs

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io#349]
It was there in earlier website - but it was not migrated and open source users are facing issues

https://frosty-austin-928e43.netlify.app/api_reference

https://signoz-community.slack.com/archives/C01HWUTP4HH/p1718804105307419?thread_ts=1718722931.189589&cid=C01HWUTP4HH

**Comment by ahmadshaheer** [comment]
This issue has been fixed in https://github.com/SigNoz/signoz-web/pull/468 by @YounixM
