### ISSUE TITLE
Issues with website docs sidebar navigation

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io#353]
### Issue 1
If a doc link is opened from google or from the in-product links - it's position in the sidebar is not highlighted:

https://www.loom.com/share/b2509284adf345b5ab2b8288e0335e26?sid=d951f6c2-4f15-4b42-896e-c2c69612ad10

### Issue 2 (reported by Pranay)
Also sometimes see 2 docs highlighted in sidebar. ([related issue](https://github.com/SigNoz/signoz-web/issues/331))

Usually happens when both are open and then closed. But not repeatable:

https://www.loom.com/share/516541e3385b442496f2e2d15d68e300?sid=1ecc4947-0740-47fa-a1ef-694e214a271a

### Issue 3 (reported by Vishal)
If a link is opened in incognito, then it's position does not get highlighted in the sidebar navigation. I think this is related to issue 1.

https://www.loom.com/share/db9132bace5f4c248d1fdbb14e30924f?sid=5becb18a-8909-419d-b7b3-2bccd70b8299

### Issue 4 
If I click on an item that is lower in the navigation bar, the corresponding doc also moves down to somewhere in the middle of the page.

https://www.loom.com/share/db9132bace5f4c248d1fdbb14e30924f?sid=5becb18a-8909-419d-b7b3-2bccd70b8299

### Proposed solution
We should try to replicate the behaviour that was in docusaurus: https://docusaurus.io/docs

Sharing a few good things from docusaurus navigation:
https://www.loom.com/share/4c25d3553ee9415f9ca5f61466066382?sid=71d2efa0-9eea-4c62-8863-1cacce27c34f

**Comment by YounixM** [comment]
Merged ✅
