### ISSUE TITLE
Add docs for Terraform Provider

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#597]
We recently made live the SigNoz Terraform provider which currently has the following ability:
-  Auto Provisioning of alerts 

We need to create a documentation telling the user how they can use this with an example and some screenshots.

Resources:
- SigNoz Terraform Docs - https://registry.terraform.io/providers/SigNoz/signoz/latest/docs
- SigNoz Terraform GitHub - https://github.com/SigNoz/terraform-provider-signoz/tree/main
- SigNoz Terraform GitHub alerts - https://github.com/SigNoz/terraform-provider-signoz/blob/main/docs/resources/alert.md
- Alerts documentation - https://signoz.io/docs/alerts/

---
**NOTE:** _This issue is part of an assignment for the [SigNoz Expert Contributors Program](https://signoz.io/signoz-expert-contributors-program/). Do not attempt/work on this issue if you haven't received an email for the assignment. _

**Comment by animeshd9** [comment]
@Calm-Rock I'll take up this issue

**Comment by prashant-shahi** [comment]
@Calm-Rock what's the status of this docs task? Has this been picked by someone?
