### ISSUE TITLE
Add HIPAA compliance logo in footer

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz.io#694]

**Comment by GeekBoySupreme** [comment]
Find the Figma [here](https://www.figma.com/design/SE5dnDz8FNsQGP7tj0Rz3B/Website?node-id=5466-11887&t=sXTEJMkinwgj6yOj-1)

<img width="994" alt="image" src="https://github.com/user-attachments/assets/2dd402a8-81ef-4252-acce-7cb9ee7f6f7a">
