### ISSUE TITLE
Add docs for Kafka Monitoring

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#717]
Relevant links and details:

- https://signoz.io/blog/kafka-monitoring-opentelemetry/
- https://github.com/shivanshuraj1333/kafka-opentelemetry-instrumentation/tree/vm-setup

Overall all these sections would be there: 
```
Local (Mac/Linux/Windows)
VM (AWS, Azure, Google Cloud)
K8s
  strimzi
Confluent
Amazon MSK
```

For the local one, the above readme is helpful; let's focus on getting that out first.

**Comment by pranay01** [comment]
@shivanshuraj1333 We discussed this in growth standup, we would need first version of basic docs from your end first

**Comment by shivanshuraj1333** [comment]
the necessary documentation had already been provided, https://signoz-team.slack.com/archives/C070V9S041L/p1724930821554109?thread_ts=1724923600.178159&cid=C070V9S041L

**Comment by Calm-Rock** [comment]
Docs PR - https://github.com/SigNoz/signoz-web/pull/823

**Comment by Calm-Rock** [comment]
Closing this as the docs are live.
