### ISSUE TITLE
Update GCP service metrics docs 

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#795]
We don't want users to use Telegraf so we should figure out a better way to do this.

Reference link to test :
- https://github.com/prometheus-community/stackdriver_exporter

**Comment by Calm-Rock** [comment]
We have this receiver now - [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudmonitoringreceiver)

Need to answer these two questions:
- Get the list of metrics possible today
- What's coming next in the development of this receiver, so we can see if we should switch right away or after some time.

**Comment by Calm-Rock** [comment]
Update:

We were able to get the metrics using the [Prometheus Stackdriver ](https://github.com/prometheus-community/stackdriver_exporter)

Ref here: https://svey-5nsw.in.signoz.cloud/dashboard/16067e6e-a2f7-4e41-9ed1-fa5e0b0db7c6?relativeTime=3d
![Image](https://github.com/user-attachments/assets/fb97a3b7-d336-4d43-b1dc-d48be7b1b8ff)

**Comment by shrutimantri** [comment]
> Get the list of metrics possible today

All the metrics that are present in GCP cloud monitoring are possible to capture, and route to Signoz.

> What's coming next in the development of this receiver, so we can see if we should switch right away or after some time.

There is no mention of any further planned developments about this receiver.

**Comment by Calm-Rock** [comment]
@shrutimantri this sounds good.

Here's a list of metrics docs that needs update:

- [x] [Cloud Functions ](https://signoz.io/docs/gcp-monitoring/gcp-fns/fns-metrics/)
- [x] [App Engine](https://signoz.io/docs/gcp-monitoring/app-engine/metrics/)
- [x] [Compute Engine](https://signoz.io/docs/gcp-monitoring/compute-engine/metrics/)
- [x] [Cloud Storage](https://signoz.io/docs/gcp-monitoring/gcs/metrics/)
- [x] [Cloud SQL](https://signoz.io/docs/gcp-monitoring/cloud-sql/metrics/)
- [x] [Cloud Load Balancer](https://signoz.io/docs/gcp-monitoring/gcp-clb/metrics/)
- [x] [VPC](https://signoz.io/docs/gcp-monitoring/vpc/metrics/)
- [x] [Cloud Run](https://signoz.io/docs/gcp-monitoring/cloud-run/metrics/)
- [x] [Cloud Monitoring](https://signoz.io/docs/gcp-monitoring/cloud-monitoring/metrics/)

**Comment by shrutimantri** [comment]
Cloud Functions: https://github.com/SigNoz/signoz-web/pull/884 
App Engine: https://github.com/SigNoz/signoz-web/pull/899 
Compute Engine: https://github.com/SigNoz/signoz-web/pull/901 
Cloud Storage: https://github.com/SigNoz/signoz-web/pull/908
Cloud SQL: https://github.com/SigNoz/signoz-web/pull/909
Cloud Load Balancer: https://github.com/SigNoz/signoz-web/pull/910

**Comment by Calm-Rock** [comment]
This is done!
