### ISSUE TITLE
Add docs for frontend monitoring - document load

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#874]
OpenTelemetry provides modules for automatic instrumentation of web applications to capture:

- Document Load - [opentelemetry-instrumentation-document-load](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-document-load)
- User Interations - [opentelemetry-instrumentation-user-interaction](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-user-interaction)

---

Expected Output:

Create detailed documentation for with steps to auto-instrumentation and visualizing the collected data in SigNoz.

Crucial things to be included in the documentation:
- How is the data collected useful ? Explain in detail how a user can use the data collected to monitor their application.
- How to set useful alerts on top of the data ?
---

Resources:
- Checkout these helpful articles 
          - [OTel Browser Instrumentation](https://www.honeycomb.io/blog/opentelemetry-browser-instrumentation)
          -  [Frontend Observability](https://docs.honeycomb.io/get-started/start-building/web/#confirm-data-is-sent)
 
- Frontend monitoring Launch week resource 
        - [Blog](https://signoz.io/newsroom/launch-week-1-day-3/)
        -  [Video](https://www.youtube.com/watch?v=pmxl11pAQRQ)

---
**NOTE:** _This issue is part of an assignment for the [SigNoz Expert Contributors Program](https://signoz.io/signoz-expert-contributors-program/). Do not attempt/work on this issue if you haven't received an email for the assignment. _

**Comment by afzal442** [comment]
I will take this up. Thanks

**Comment by vikrantgupta25** [comment]
@Calm-Rock is this done ?

**Comment by Calm-Rock** [comment]
> @Calm-Rock is this done ? 

Yes - https://signoz.io/docs/frontend-monitoring/document-load/
