### ISSUE TITLE
Docs for NodeJS Winston transport and Pino transport

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#878]
Send logs from Node.js (via Winston or Pino) directly to SigNoz Cloud without the need for Otel collectors.

- [ ] Add documentation for configuring Winston and Pino transports to send logs directly to SigNoz Cloud without requiring an Otel collector.
- [ ] Provide sample code and steps to achieve this for both Winston and Pino transports.

--- 
The final output would have two different documents, one for Winston and the other for Pino.

---

Resources:
- https://www.npmjs.com/package/@opentelemetry/winston-transport
- https://github.com/pinojs/pino-opentelemetry-transport

---
**NOTE:** _This issue is part of an assignment for the [SigNoz Expert Contributors Program](https://signoz.io/signoz-expert-contributors-program/). Do not attempt/work on this issue if you haven't received an email for the assignment. _

**Comment by animeshd9** [comment]
@Calm-Rock I'll take up the issue
