### ISSUE TITLE
Create Documentation for OpenTelemetry Bridges for Logrus and Zap

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#879]
We need documentation for using OpenTelemetry bridges with the Logrus and Zap logging libraries to send logs to SigNoz Cloud

Scope of the documentation:

- Create step-by-step documentation for using the OpenTelemetry bridges for Logrus and Zap.
- Show how to inject trace and span IDs into logs.
- Configure the setup to send these logs to SigNoz.
- Provide a working example for each logging library.

---

Output should be in the form of two different documents, one for each logging library.

--- 

Resource:
- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges

---
**NOTE:** _This issue is part of an assignment for the [SigNoz Expert Contributors Program](https://signoz.io/signoz-expert-contributors-program/). Do not attempt/work on this issue if you haven't received an email for the assignment. _

**Comment by AkshayAwate** [comment]
I'm working on this issue.

**Comment by bss-t** [comment]
Will pick it up.
