### ISSUE TITLE
Docs for monitoring Docker Container metrics

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz.io#880]
We have the docs for getting the [Docker container logs](https://signoz.io/docs/userguide/collect_docker_logs/) but not docker container metrics.

This will involve the use of dockerstats receiver.

---
Resources:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/dockerstatsreceiver/README.md

-----

**NOTE:** _This issue is part of an assignment for the [SigNoz Expert Contributors Program](https://signoz.io/signoz-expert-contributors-program/). Do not attempt/work on this issue if you haven't received an email for the assignment. _

**Comment by afzal442** [comment]
I will take this up

/assign @afzal442

**Comment by karanveersingh5623** [comment]
Already started on this 
/assign @karanveersingh5623

**Comment by afzal442** [comment]
sorry @karanveersingh5623 I have been part of this job assignments. find other issues.

**Comment by Calm-Rock** [comment]
Hey @afzal442 @karanveersingh5623. 

This issue is available to anyone who has received the assignment email for the SigNoz Expert Contributors Program. If you've received that email, feel free to take this up.

If you're not part of the Expert Contributors Program, please refrain from working on this issue. We have many other open issues that you can contribute to independently.

Thanks for your understanding!

The details about how you should submit the assignment is mentioned in the Notion Document shared with you for the assignment.

**Comment by afzal442** [comment]
That's right. I agree with you. I showed up my interest on this first as part of ECP. There are bunch of issues out there related to that. That's why I told him to find others. And that's the spirit of open source culture. Hope that makes sense. Thanks

**Comment by afzal442** [comment]
@Calm-Rock could you tell me before I proceed whether I should combine docs for container metrics with the existing sending logs docs or make it separately?

Can we use this dashboard https://github.com/SigNoz/dashboards/blob/main/container-metrics/docker?
