### ISSUE TITLE
File Name correction for fluentforward Port

### ISSUE THREAD

**Issue by harshit-paneri** [SigNoz/signoz.io#911]
In FLuentd to Signoz doc, 
Point: Steps to receive logs from FluentD
![image](https://github.com/user-attachments/assets/210dd528-deb9-4fe5-b77f-dc33d97802d7)

Expose the port in port for otel-collector in `docker-compose.yaml `file present in `deploy/docker/clickhouse-setup` to Expose the port in port for otel-collector in `otel-collector-config.yaml `file present in `deploy/docker/clickhouse-setup`

**Comment by Calm-Rock** [comment]
Thanks for creating the issue @harshit-paneri!

Do you want to work on creating a PR to fix this ?

**Comment by harshit-paneri** [comment]
> Thanks for creating the issue @harshit-paneri!
> 
> Do you want to work on creating a PR to fix this ?

Yes and label It on documentation

**Comment by harshit-paneri** [comment]
Hey @Calm-Rock I raise a PR #912.

**Comment by Calm-Rock** [comment]
Thanks @harshit-paneri. Have assigned a reviewer.

**Comment by harshit-paneri** [comment]
> Thanks @harshit-paneri. Have assigned a reviewer.

Great 🚀
