### ISSUE TITLE
improve `OpenTelemetry Setup in a Nodejs Application` article

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [SigNoz/signoz.io#917]
In this(https://signoz.io/opentelemetry/nodejs/) article, we are using two packages: express and cors. However, the dependency installation step is missing the `cors` package, so it would be great to add the `cors` package to the dependency installation step.

**Comment by Sachin-chaurasiya** [comment]
@YounixM , I would like to work on this issue, could you please assign it to me? thanks!

**Comment by Calm-Rock** [comment]
@Sachin-chaurasiya, thanks for the issue. I have assigned it to you.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya, thanks for the issue. I have assigned it to you.

Thanks @Calm-Rock , raised a PR https://github.com/SigNoz/signoz-web/pull/918, please review.
