### ISSUE TITLE
Broken pricing page

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz.io#954]
Maybe only specific to firefox
https://www.loom.com/share/72cb6d0c537a4d87af3d5bba403ee5d5

**Comment by soheb-btw** [comment]
@makeavish I would like to work on this, could please assign this to me.

**Comment by makeavish** [comment]
> @makeavish I would like to work on this, could please assign this to me.

Done, please provide an update on this issue soon or else we would pick internally
cc: @YounixM

**Comment by soheb-btw** [comment]
![image](https://github.com/user-attachments/assets/0c90321b-f0d2-4f4a-8d3e-0cbbe954848d)

@makeavish in Pricing.tsx for <WhySelectSignoz> we are passing isInPricingPage prop, however its not defined the component and this is what causing the issue.

**Comment by soheb-btw** [comment]
@makeavish the loading issue is coming when we are loading signoz.svg in img tag at line 26 in community-edition component. the svg is to large and taking time to load. I tested with a smaller similar svg which is in navbar and its working fine, however this makes the logo little blurry. I am attaching the screenshot with smaller svg 

![image](https://github.com/user-attachments/assets/42d08ddb-018d-41b3-a5be-38d9eff039c9)

let me know how you want to proceed with this

**Comment by makeavish** [comment]
> @makeavish the loading issue is coming when we are loading signoz.svg in img tag at line 26 in community-edition component. the svg is to large and taking time to load. I tested with a smaller similar svg which is in navbar and its working fine, however this makes the logo little blurry. I am attaching the screenshot with smaller svg
> 
> ![image](https://private-user-images.githubusercontent.com/59690289/385298264-42d08ddb-018d-41b3-a5be-38d9eff039c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzM4OTUsIm5iZiI6MTczMTQzMzU5NSwicGF0aCI6Ii81OTY5MDI4OS8zODUyOTgyNjQtNDJkMDhkZGItMDE4ZC00MWIzLWE1YmUtMzhkOWVmZjAzOWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE3NDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzAyZWE1M2YxYTBlNDRiMDcwMTFlMzEwOGMxNTEyNzEwNWRkNDU1NmFmM2E3ZGY3ZTM5NTQ0MmQzNTRiMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-FvTBCh7_KzW2TM_v0kTBKvjHu8Su9Ett-RlR8HwKfo)
> 
> let me know how you want to proceed with this

@YounixM Please check

**Comment by YounixM** [comment]
@soheb-btw : Can you try using https://svgo.dev/ to optimize the logo and use it ?

**Comment by soheb-btw** [comment]
@YounixM I tried it with svgo svg optimized file and its still loading slow, however I have modified the original svg file, and now its loading fine. I am attaching the screenshot below if it looks fine let know I will raise the PR 

![image](https://github.com/user-attachments/assets/e989a07f-35b2-49c7-8211-08b7304e4e9a)

**Comment by YounixM** [comment]
Sure @soheb-btw , please create a PR and share with us.
