### ISSUE TITLE
The doc page is 404

### ISSUE THREAD

**Issue by seanmars** [SigNoz/signoz.io#974]
Currently the [doc page](https://signoz.io/docs/) result 404

**Comment by Calm-Rock** [comment]
@seanmars thanks for raising the issue!

Can you tell when did this link started throwing 404 for you ? Was it working fine earlier ?

**Comment by Calm-Rock** [comment]
Hey @seanmars !
This issue is fixed. You can checkout the [docs page ](https://signoz.io/docs/introduction/)now.
Thanks!
